name: gawebWeEksab
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  share: 0.6.5
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.18.1+1
  random_string: ^2.1.0
  url_launcher: ^5.7.2
  firebase_messaging: ^7.0.3
  animations: ^1.1.2
  flutter_native_splash: ^0.1.9
  firebase_admob: ^0.10.0
  path_provider: ^1.6.18
  path: ^1.7.0

#  meta: ^1.2.3
#  stack_trace: ^1.9.5
#



flutter_native_splash:
  image: images/MyGo.png
  color: "FFFFFF"
  android_disable_fullscreen: false



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Pacifico
     fonts:
        - asset: fonts/Pacifico-Regular.ttf


   - family: ReemKufi
     fonts:
        - asset: fonts/ReemKufi-Regular.ttf


   - family: Rakkas
     fonts:
        - asset: fonts/Rakkas-Regular.ttf

   - family: Lalezar
     fonts:
       - asset: fonts/Lalezar-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
